#BSUB -L /bin/bash              
#BSUB -J pilonpolish
#BSUB -o stdout.%J
#BSUB -e stderr.%J 
#BSUB -n 20
#BSUB -R "span[ptile=20]" 
#BSUB -R "rusage[mem=12300]"
#BSUB -M 12300
#BSUB -R "select[mem256gb]"
#BSUB -W 168:00
#BSUB -u edegreef@ucdavis.edu
#BSUB -B -N

cd /scratch/user/edegreef/ref_genome/pilon1;
module load Pilon/1.23-Java-11;
java -Xmx220G -jar $EBROOTPILON/pilon.jar --genome PUMA.arrow.fasta --frags sortedillumalign.bam --output PUMA --threads 8
