#BSUB -L /bin/bash              
#BSUB -J sortbam2
#BSUB -n 8
#BSUB -R "span[ptile=8]" 
#BSUB -R "rusage[mem=5000]"
#BSUB -M 5000
#BSUB -W 48:00
#BSUB -o stdout.%J
#BSUB -e stderr.%J 
#BSUB -u edegreef@ucdavis.edu
#BSUB -B -N

cd /scratch/user/edegreef/ref_genome/pilon1;
module load SAMtools/1.9-intel-2018b;
samtools sort -@ 8 -m 4G -o sortedillumalign.phased.bam illumalign.phased.bam
samtools index sortedillumalign.phased.bam;

#Looking at output of samtools stats helps determine which option to use for reading bam files in Pilon
samtools stats sortedillumalign.phased.bam
