#BSUB -L /bin/bash              
#BSUB -J pilonpolish2
#BSUB -o stdout.%J
#BSUB -e stderr.%J 
#BSUB -n 40
#BSUB -R "select[mem1tb]"
#BSUB -R "span[ptile=40]" 
#BSUB -R "rusage[mem=24750]"
#BSUB -M 24750
#BSUB -q xlarge
#BSUB -W 168:00
#BSUB -u edegreef@ucdavis.edu
#BSUB -B -N

cd /scratch/user/edegreef/ref_genome/pilon1;
module load Westmere;
module load Pilon/1.23-Java-11;
java -Xmx300G -jar $EBROOTPILON/pilon.jar --genome PUMAphased.arrow.fasta --frags sortedillumalign.phased.bam --output PUMAphased --threads 40
