#BSUB -L /bin/bash              
#BSUB -J buscolong2
#BSUB -n 1
#BSUB -R "span[ptile=1]" 
#BSUB -R "rusage[mem=5000]"
#BSUB -M 5000
#BSUB -W 168:00
#BSUB -o stdout.%J
#BSUB -e stderr.%J 
#BSUB -u edegreef@ucdavis.edu
#BSUB -B -N

cd /scratch/user/edegreef/ref_genome/arkslinks/phased_genome/buscolong2_round;
module load BUSCO/3.0.2-intel-2017b-Python-3.6.3;

if [ ! -d "$SCRATCH/my_augustus_config/config" ]; then
  echo "Copying AUGUSTUS config directories to $SCRATCH/my_augustus_config"
  mkdir $SCRATCH/my_augustus_config
    if [ "-$EBROOTAUGUSTUS" == "-" ]; then
        echo "Augustus module not loaded"; exit 1
    fi
  rsync -r $EBROOTAUGUSTUS/ $SCRATCH/my_augustus_config
  chmod -R 755 $SCRATCH/my_augustus_config
fi
export AUGUSTUS_CONFIG_PATH="$SCRATCH/my_augustus_config/config"

python $EBROOTBUSCO/scripts/run_BUSCO.py -i PUMAphased_11212019.fasta -m genome -l /scratch/datasets/BUSCO/v3.0.2/aves_odb9 -o buscolong_stats -c 1 -sp chicken


