#BSUB -L /bin/bash              
#BSUB -J arkslinks
#BSUB -n 20
#BSUB -R "span[ptile=20]" 
#BSUB -R "rusage[mem=2700]"
#BSUB -M 2700
#BSUB -W 24:00
#BSUB -o stdout.%J
#BSUB -e stderr.%J 
#BSUB -u edegreef@ucdavis.edu
#BSUB -B -N

cd /scratch/user/edegreef/ref_genome/arkslinks
module load ARKS/1.0.4-foss-2018b-Python-2.7.15

arks-make arks draft=PUMA2.arrow.pilon reads=barcoded

#arks will produce multiple outputs, the one with the updated genome is named <input>_c5_m50-10000_k30_r0.05_e30000_z500_l5_a0.3.scaffolds.fa
