#BSUB -L /bin/bash              
#BSUB -J busco_long
#BSUB -n 1
#BSUB -R "span[ptile=1]" 
#BSUB -R "rusage[mem=6000]"
#BSUB -M 6000
#BSUB -W 168:00
#BSUB -o stdout.%J
#BSUB -e stderr.%J 
#BSUB -u edegreef@ucdavis.edu
#BSUB -B -N

cd /scratch/user/edegreef/ref_genome/busco
module load BUSCO/4.0.5-foss-2019b-Python-3.7.4

if [ ! -d "$SCRATCH/my_augustus_config/config" ]; then
  echo "Copying AUGUSTUS config directories to $SCRATCH/my_augustus_config"
  mkdir $SCRATCH/my_augustus_config
    if [ "-$EBROOTAUGUSTUS" == "-" ]; then
        echo "Augustus module not loaded"; exit 1
    fi
  rsync -r $EBROOTAUGUSTUS/ $SCRATCH/my_augustus_config
  chmod -R 755 $SCRATCH/my_augustus_config
fi
export AUGUSTUS_CONFIG_PATH="$SCRATCH/my_augustus_config/config"

busco --offline --in /scratch/user/edegreef/ref_genome/PUMA2_03022020.fasta --mode genome --lineage /scratch/user/edegreef/ref_genome/busco/aves_odb10 -o busco_stats_run2_long -c 1 --augustus_species chicken
