#BSUB -L /bin/bash              
#BSUB -J blastnA
#BSUB -n 8
#BSUB -R "span[ptile=8]" 
#BSUB -R "rusage[mem=2500]"
#BSUB -M 2500
#BSUB -W 168:00
#BSUB -o stdout.%J
#BSUB -e stderr.%J 
#BSUB -u edegreef@ucdavis.edu
#BSUB -B -N

cd /scratch/user/edegreef/ref_genome/contaminants

module load BLAST+/2.9.0-iimpi-2019a

export BLASTDB=$BLASTDB:/scratch/user/edegreef/ref_genome/ncbi/

while read prefix
do

blastn -query split_dir/"$prefix" -db /scratch/datasets/BLAST/nt -evalue 1e-5 -perc_identity 70 -num_threads 8 -out blast_out/"$prefix"_outfile.txt -outfmt "6 qacc sacc pident length mismatch gapopen qstart qend sstart send evalue bitscore staxids sscinames scomnames sskingdoms"

export LANG=C; export LC_ALL=C; sort -k1,1 -k12,12gr -k11,11g -k3,3gr blast_out/"$prefix"_outfile.txt | sort -u -k1,1 --merge > best_hits/"$prefix"_bestHits

done < listA_0-600