#BSUB -L /bin/bash              
#BSUB -J blastp_update
#BSUB -n 8
#BSUB -R "span[ptile=8]" 
#BSUB -R "rusage[mem=2500]"
#BSUB -M 2500
#BSUB -W 48:00
#BSUB -o stdout.%J
#BSUB -e stderr.%J 
#BSUB -u edegreef@ucdavis.edu
#BSUB -B -N

cd /scratch/user/edegreef/ref_genome/annotation
module load MAKER/2.31.10-intel-2017A-Python-2.7.12

maker_functional_gff uniprot/uniprot_COFL_REJU_ZEFI.fasta PUMA.uniprot.renamed.blastp PUMA.maker.renamed.gff > PUMA.maker.renamed.putative_function.gff

maker_functional_fasta uniprot/uniprot_COFL_REJU_ZEFI.fasta PUMA.uniprot.renamed.blastp PUMA.maker.proteins.renamed.fasta > PUMA.maker.proteins.renamed.putative_function.fasta

maker_functional_fasta uniprot/uniprot_COFL_REJU_ZEFI.fasta PUMA.uniprot.renamed.blastp PUMA.maker.transcripts.renamed.fasta > PUMA.maker.transcripts.renamed.putative_function.fasta